### ISSUE TITLE
Transfert project to IIS

### ISSUE THREAD

**Issue by Nitro1977** [rjperes/DevelopmentWithADot.AspNetSignalRVideoStreaming#3]
Hi Ricardo.........very very good project!!

I download your project and still RAN on Visual Studio 2015......all the feature works!!
I put the project in IIS 7.5 on my Windows 7 and on a page set as SOURCE=TRUE dont call the wecam API and in the 2 box source & recived don't see anithings

**Comment by rjperes** [comment]
Hi, Nitro!
No idea... let me try to find out. If you happen to discover, please let me know!

**Comment by Nitro1977** [comment]
Ok...it will be done!!
i made a few debug in the Javascript function startStream()...........in VS debug when i call the function startStream after a few ms the hubConnection fire the ".done".........in IIS 7.5 they dont fire ever the .done for the HubConnection................. :-(

**Comment by Nitro1977** [comment]
Hi Ricardo...........in this 2 days i do one million of test and configuration........but........don't work...:-(( i'don't understand why your project doesn't work on IIS...............

**Comment by rjperes** [comment]
Please see these links:
https://stackoverflow.com/questions/38802347/self-host-signalr-in-windows-10
https://stackoverflow.com/questions/16900536/signalr-applications-do-not-work-under-iis
https://stackoverflow.com/questions/8053229/signalr-hub-not-loading-in-iis-7-but-working-correctly-in-visual-studio

**Comment by Nitro1977** [comment]
Ok......i do a little step over..............now when i ran the web page with the /?Source=true the debugger tell me a sintax error in JQuery e JQuery.SignalR library.........if i click on continue & continue the debugger tell me $ not defined........!!.........why now dont load the .js library.........!?!?......only with the parameter in the nav bar Source=true..........:-((

**Comment by rjperes** [comment]
if $ is not defined it means my JavaScript code is executing too soon...
Maybe you can delay it, for example, running only when the document is ready:
document.addEventListener('ready', function() { ... });

**Comment by Nitro1977** [comment]
Sorry Ricardo........this last problem was the syntax /?.......i replace with ? and the error disappear..........but the connection fail again............... :-(

**Comment by rjperes** [comment]
I'm sorry but right now I can't help... will try to replicate it later.
Thanks for the letting me know.

**Comment by Nitro1977** [comment]
ok thank a lot Ricardo........i put my project in stand-by.......i'l waiting if you can test the application on IIS

**Comment by Nitro1977** [comment]
Hi Ricardo........... I SOLVED THE PROBLEM!!
The problem was that I did not "publish" the site from Visual Studio in my IIS.
When I made it public at Visual Studio it all started to work

Thanks for all
By
Nicola

**Comment by rjperes** [comment]
That is great! Thanks a lot for sharing!
